name: CI - Wheel Tests (Continuous)
permissions:
      contents: read

on:
  schedule:
    - cron: "0 0 * * *" # Run once per day
  workflow_dispatch: # allows triggering the workflow run manually
  push:
    branches: ["develop"]
    paths:
      - ".github/workflows/continuous_tests.yml"
      - ".github/workflows/build_artifacts.yml"
      - ".github/workflows/pytest_cpu.yml"
      - ".github/workflows/pytest_cuda.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'release/') && github.ref != 'main' }}

jobs:
  build-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
    name: "Build artifacts"
    with:
        runner: "linux-x86-n2-16"
        artifact: "test"

  build-test-artifact:
    uses: ./.github/workflows/build_artifacts.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
            runner: ["linux-x86-n2-16", "linux-arm64-t2a-48", "windows-x86-n2-16"]
            artifact: ["test-artifacts"]
            python: ["3.11"]
    # Note: For reasons unknown, Github actions groups jobs with the same top-level name in the
    # dashboard only if we use an expression in the "name" field. Otherwise, it appends the matrix
    # values to the name and creates a separate entry for each matrix combination.
    name: "Build ${{ format('{0}', 'test') }} artifacts"
    with:
        runner: ${{ matrix.runner }}
        artifact: ${{ matrix.artifact }}
        python: ${{ matrix.python }}

  build-cuda-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          # Python values need to match the matrix stategy in the CUDA tests job below
          runner: ["linux-x86-n2-16"]
          artifact: ["test", "test-artifacts"]
          python: ["3.11",]
          cuda-version: ["12", "13"]
    name: "Build ${{ format('{0}', 'CUDA') }} artifacts"
    with:
      runner: ${{ matrix.runner }}
      artifact: ${{ matrix.artifact }}
      python: ${{ matrix.python }}
      cuda-version: ${{ matrix.cuda-version }}

  run-pytest-cpu:
    # Run test jobs even if the build job fails. Avoids losing test coverage if a single unrelated
    # build job fails. E.g Windows build job fails but everything else succeeds. In this case, we
    # still want to run the tests for other platforms.
    if: ${{ !cancelled() }}
    needs: [build-artifacts, build-test-artifact]
    uses: ./.github/workflows/pytest_cpu.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-n2-64", "linux-arm64-t2a-48", "windows-x86-n2-64"]
          python: ["3.11",]
    name: "Pytest CPU (artifacts version =  ${{ format('{0}', 'head') }})"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}

  run-pytest-cuda:
    if: ${{ !cancelled() }}
    needs: [build-artifacts, build-test-artifact, build-cuda-artifacts]
    uses: ./.github/workflows/pytest_cuda.yml
    strategy:
        fail-fast: false # don't cancel all jobs on failure
        matrix:
          runner: ["linux-x86-g2-48-l4-4gpu",]
          python: ["3.11",]

          cuda: ["12.1", "12.9", "13"]

    name: "Pytest CUDA (artifacts version =  ${{ format('{0}', 'head') }})"
    with:
      runner: ${{ matrix.runner }}
      python: ${{ matrix.python }}
      cuda-version:  ${{ matrix.cuda }}

