name: Culprit Finder Workflow

on:
  workflow_dispatch:
    inputs:
      workflow-to-debug:
        description: "Which workflow should be run?"
        type: string
        default: ""
        required: true
      json_vars:
        type: string
        description: 'A JSON string of key-value pairs that will be passed as environment variables to the workflow. (e.g., {"NAME": "test", "VERSION": "1.2.3"})'
        required: false
        default: '{}'
      cross_repo_commit_sha:
        type: string
        description: 'The SHA of the commit to test against.'
        required: false
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}


jobs:
  bisect-test-workflow:
    if: ${{ inputs.workflow-to-debug == 'dev_workflow.yml' }}
    uses: ./.github/workflows/dev_workflow.yml
    name: Bisect Test Workflow
    with:
      json_vars: ${{ inputs.json_vars }}

  bisect-python-tests:
    if: ${{ inputs.workflow-to-debug == 'python_tests.yml' }}
    uses: ./.github/workflows/python_tests.yml
    name: Bisect Python Tests
    with:
      json_vars: ${{ inputs.json_vars }}
      py_hello_world_sha: ${{ inputs.cross_repo_commit_sha }}

  bisect-python-tests-head:
    if: ${{ inputs.workflow-to-debug == 'python_tests_head.yml' }}
    uses: ./.github/workflows/python_tests_head.yml
    name: Bisect Python Tests (Head)
    with:
      json_vars: ${{ inputs.json_vars }}
