name: Python Tests Head
on:
  push:
    branches:
      - develop
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      json_vars:
        type: string
        description: 'A JSON string of key-value pairs that will be passed as environment variables to the workflow. (e.g., {"NAME": "test", "VERSION": "1.2.3"})'
        required: false
        default: '{}'
      py_hello_world_sha:
        type: string
        description: 'The SHA of the py-hello-world package to test against.'
        required: false
        default: 'main'
  workflow_call:
    inputs:
      json_vars:
        type: string
        description: 'A JSON string of key-value pairs that will be passed as environment variables to the workflow. (e.g., {"NAME": "test", "VERSION": "1.2.3"})'
        required: false
        default: '{}'
      py_hello_world_sha:
        type: string
        description: 'The SHA of the py-hello-world package to test against.'
        required: false
        default: 'main'

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install specific package version
        run: |
          # Priority: 1. Input parameter, 2. 'main' default
          TARGET_SHA="${{ inputs.py_hello_world_sha }}"
          TARGET_SHA=${TARGET_SHA:-main}
          
          echo "Installing version: $TARGET_SHA"
          pip install "git+https://github.com/danielibarrola/python-hello-world.git@$TARGET_SHA"
      - name: Test
        run: python tests/test_hello_world.py

  build:
    runs-on: ubuntu-latest
    name: Test Build
    steps:
      - name: Build
        run: |
          echo "Current SHA: ${{ github.sha }}"
          echo "Build Job"
          echo "Fail!"
          exit 1